### ISSUE TITLE
Major task list

### ISSUE THREAD

**Issue by markwang0** [passaH2O/pygeoflood#1]
Major task list
---
- [ ] Make sphinx website and documentation
  - User guide
  - Jupyter notebook tutorials
  - Working examples
- [ ] Calculate HAND with D-infinity flow directions
  - if our WhiteboxTools feature request is not implemented
  - jblindsay/whitebox-tools#403
- [ ] Unit tests
- [ ] Integrate FSM from [RichDEM ](https://github.com/r-barnes/richdem/blob/c5a183ada30fbd1b8587121e0d313b4cda9390c0/wrappers/pyrichdem/examples/fill_spill_merge.py#L24) (pluvial)
- [ ] Integrate [c-HAND](https://github.com/passaH2O/c-HAND) (coastal)
- [ ] Method to load example data
- [ ] Automate fetching NWM data, catchments, DEMs, streamlines, etc.
- [ ] Plotting library
- [ ] Evaluation library
  - Compare with validation data (remote sensing or hydrodynamic model)
  - TP/TN/FP/FN maps
- [ ] GitHub workflow to format code on push
- [ ] Live view web application
